name: Check queries

on:
  push:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_compilation:
    name: Build
    uses: ./.github/workflows/test-core.yml
    with:
      type: "queries"
